# Generated by Django 4.1.1 on 2022-09-19 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quest_app', '0002_product_alter_category_description_delete_poduct_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('S_No', models.IntegerField()),
                ('Card_Number', models.IntegerField()),
                ('Expiry_details', models.IntegerField()),
                ('Cardholder_Name', models.CharField(max_length=150)),
            ],
        ),
    ]
