# Generated by Django 4.1.1 on 2022-09-19 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quest_app', '0003_card_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card_details',
            name='Expiry_details',
            field=models.DateField(),
        ),
    ]
