# Generated by Django 4.1.1 on 2022-09-19 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quest_app', '0004_alter_card_details_expiry_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card_details',
            name='Expiry_details',
            field=models.CharField(max_length=150),
        ),
    ]
